elasticsearch_version: "8.12.0"

elasticsearch_cluster_name: "asapflow-es"
elasticsearch_node_name: "{{ ansible_hostname }}"
elasticsearch_discovery_type: single-node

elasticsearch_data_path: /var/lib/elasticsearch
elasticsearch_logs_path: /var/log/elasticsearch

elasticsearch_network_host: 0.0.0.0
elasticsearch_http_port: 9200

# Segurança
elasticsearch_enable_cis: true
elasticsearch_enable_security: true
elasticsearch_app_user: asapflow_app
# As senhas serão solicitadas via prompt no playbook.yml


#backup e snapshot
backup: false   # <- flag principal

elasticsearch_snapshot_repo: s3_backup
elasticsearch_snapshot_bucket: meu-bucket-backup-es
elasticsearch_snapshot_region: us-east-1
elasticsearch_snapshot_base_path: elasticsearch/snapshots

elasticsearch_snapshot_schedule: "0 0 2 * * ?"   # 02:00
elasticsearch_snapshot_retention_days: 30
elasticsearch_snapshot_min_count: 7
elasticsearch_snapshot_max_count: 30
